src/Entity/Score.php
<?php

namespace App\Entity;

use App\Repository\ScoreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScoreRepository::class)
 */
class Score
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_perfect;

    /**
     * @ORM\OneToMany(targetEntity=Quizz::class, mappedBy="score")
     */
    private $quizzs;

    public function __construct()
    {
        $this->quizzs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRate(): ?string
    {
        return $this->rate;
    }

    public function setRate(string $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getIsPerfect(): ?bool
    {
        return $this->is_perfect;
    }

    public function setIsPerfect(bool $is_perfect): self
    {
        $this->is_perfect = $is_perfect;

        return $this;
    }

    /**
     * @return Collection|Quizz[]
     */
    public function getQuizzs(): Collection
    {
        return $this->quizzs;
    }

    public function addQuizz(Quizz $quizz): self
    {
        if (!$this->quizzs->contains($quizz)) {
            $this->quizzs[] = $quizz;
            $quizz->setScore($this);
        }

        return $this;
    }

    public function removeQuizz(Quizz $quizz): self
    {
        if ($this->quizzs->removeElement($quizz)) {
            // set the owning side to null (unless already changed)
            if ($quizz->getScore() === $this) {
                $quizz->setScore(null);
            }
        }

        return $this;
    }
}

src/Form/ScoreType.php
<?php

namespace App\Form;

use App\Entity\Score;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScoreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('rate')
            ->add('is_perfect')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Score::class,
        ]);
    }
}

src/Controller/ScoreController.php
<?php

namespace App\Controller;

use App\Entity\Score;
use App\Form\ScoreType;
use App\Repository\ScoreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/score")
 */
class ScoreController extends AbstractController
{
    /**
     * @Route("/", name="score_index", methods={"GET"})
     */
    public function index(ScoreRepository $scoreRepository): Response
    {
        return $this->render('score/index.html.twig', [
            'scores' => $scoreRepository->findBestScores(),
        ]);
    }

    /**
     * @Route("/new", name="score_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $score = new Score();
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($score);
            $entityManager->flush();

            return $this->redirectToRoute('score_index');
        }

        return $this->render('score/new.html.twig', [
            'score' => $score,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="score_show", methods={"GET"})
     */
    public function show(Score $score): Response
    {
        return $this->render('score/show.html.twig', [
            'score' => $score,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="score_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Score $score): Response
    {
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('score_index');
        }

        return $this->render('score/edit.html.twig', [
            'score' => $score,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="score_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Score $score): Response
    {
        if ($this->isCsrfTokenValid('delete'.$score->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($score);
            $entityManager->flush();
        }

        return $this->redirectToRoute('score_index');
    }
}

templates/score/_delete_form.html.twig
<form method="post" action="{{ path('score_delete', {'id': score.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ score.id) }}">
    <button class="btn">Delete</button>
</form>

templates/score/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Score{% endblock %}

{% block body %}
    <h1>Edit Score</h1>

    {{ include('score/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('score_index') }}">back to list</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}

templates/score/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score index{% endblock %}

{% block body %}
    <h1>TOP 10 SCORES</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Classement</th>
                <th>Score</th>
                <th>Joueur</th>
            </tr>
        </thead>
        <tbody>
        {% for score in scores %}
            <tr>
                <td>{{ score.id }}</td>
                <td>{{ score.rate }}</td>
                <td>{{ score.quizz.user }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Pas de résultats</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/score/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Score{% endblock %}

{% block body %}
    <h1>Create new Score</h1>

    {{ include('score/_form.html.twig') }}

    <a href="{{ path('score_index') }}">back to list</a>
{% endblock %}

templates/score/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score{% endblock %}

{% block body %}
    <h1>Score</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ score.id }}</td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>{{ score.rate }}</td>
            </tr>
            <tr>
                <th>Is_perfect</th>
                <td>{{ score.isPerfect ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('score_index') }}">back to list</a>

    <a href="{{ path('score_edit', {'id': score.id}) }}">edit</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}